//next components
import Head from "next/head";

//components
import { Layout } from "../components/Layout";

export default function Home() {
  return (
    <>
      <Head>
        <title>Ryan Lima - Portfólio</title>

        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <link rel="icon" href="/assets/images/favicon-perfil.png" />
      </Head>

      <Layout />
    </>
  );
}
